#!/bin/bash
gnuplot << eor 
set terminal pngcairo size 1600,800 enhanced font 'Verdana,14' 
set linestyle 1 lt 1 lc 1 lw 1 pt 7 pi -1 ps 1
set linestyle 2 lt 1 lc 3 lw 1 pt 7 pi -1 ps 1
set output 'multiplot.png'
set multiplot layout 1,2 title "Multiple Geometries, W = 50cm, 20 Mesh pts, Source2 = 0"

set datafile separator ","

set xlabel "Width [cm]" 
set ylabel "Flux"
set origin 0.0, 0.0
plot "test1.csv" u 1:2 w linespoints ls 1 t "Numerical - Cylinder" 
set origin 0.5, 0.0
plot "test.csv" u 1:2 w linespoints ls 2 t "Numerical - Sphere" 
unset multiplot
unset output
eor

