#!/bin/bash
gnuplot << eor 
#  USE THESE FOR POINTS ON LINE
set linestyle 1 lt 1 lc 1 lw 1 pt 7 pi -1 ps 1
set linestyle 2 lt 1 lc 3 lw 1 pt 7 pi -1 ps 1
set linestyle 3 lt 1 lc 2 lw 1 pt 7 pi -1 ps 1
set linestyle 4 lt 1 lc 4 lw 1 pt 7 pi -1 ps 1
set linestyle 5 lt 1 lc 7 lw 1 pt 9 pi -1 ps 1
set linestyle 6 lt 1 lc 7 lw 1 pt 8 pi -1 ps 1

#  USE THESE FOR NO POINTS
#set linestyle 1 lt 1 lc 1 lw 1
#set linestyle 2 lt 1 lc 3 lw 1

set terminal pngcairo size 1200,800 enhanced font 'Verdana,14'
set output 'plot.png'
set datafile separator ","
set title "Project 3 - 4 Group + Summations - Spherical - H20 Moderator"
set xlabel "Width [cm]"
set ylabel "Flux"
#set yrange [0:100 < * < 100000000]

# WITH POINTS
plot "proj3_data.csv" u 1:2 w linespoints ls 1 t "Group 1",\
     "proj3_data.csv" u 1:3 w linespoints ls 2 t "Group 2",\
     "proj3_data.csv" u 1:4 w linespoints ls 3 t "Group 3",\
     "proj3_data.csv" u 1:5 w linespoints ls 4 t "Group 4",\
     "proj3_data.csv" u 1:(column(2)+column(3)+column(4)+column(5)) w linespoints ls 5 t "Sum: All Groups",\
     "proj3_data.csv" u 1:(column(3)+column(4)+column(5)) w linespoints ls 6 t "Sum: Thermal Groups"

#NO POINTS
#plot "proj3_data.csv" u 1:2 w l ls 1 t "Numerical",  \
#     "proj3_data.csv" u 1:3 w l ls 2 t "Analytical"



eor

