#!/bin/bash
gnuplot << eor 
#  USE THESE FOR POINTS ON LINE
set linestyle 1 lt 1 lc 1 lw 1 pt 7 pi -1 ps 1
set linestyle 2 lt 1 lc 3 lw 1 pt 7 pi -1 ps 1

#  USE THESE FOR NO POINTS
#set linestyle 1 lt 1 lc 1 lw 1
#set linestyle 2 lt 1 lc 3 lw 1

set terminal pngcairo size 1200,800 enhanced font 'Verdana,16'
set output '1_group.png'
set datafile separator ","
set title "Project 2: Bonus Question - 1Group Multiplier with Hydrogen Moderator"
set xlabel "Width [cm]"
set ylabel "Flux"
#set yrange [0:100 < * < 100000000]

# WITH POINTS
plot "test.csv" u 1:2 w linespoints ls 1 t "Flux"

#NO POINTS
#plot "test.csv" u 1:2 w l ls 1 t "Numerical",  \
#     "test.csv" u 1:3 w l ls 2 t "Analytical"



eor

