#!/bin/bash

#This file runs the ne470_project1_6.f08, then feeds the data to
#a csv file "test.txt", then creates and saves a plot of the data
#called singleplot.png

#To change the parameters that are fed to the fortran script,
#edit "fortran_config.txt" at the appropriate line

echo "Running NE470 Project 1 Script - Group1"
cat fortran_config.txt | ./ne470_project1_6.exe
echo "Fortran Execution Completed"
./singleplot
echo "Plot Written"

